spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/ik_test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root  #用户名
    password:   #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
 
 
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.bean